### PR TITLE
internal/rest/resources: Return joinInfo even on error

### PR DESCRIPTION
**Pull request by claudiubelu**
When joining a cluster, if any error occurs after becoming a cluster member, we're not removing the current node from the cluster, even though we should.

That is because in ``joinWithToken`` after calling ``internalClient.AddClusterMember`` and getting a ``joinInfo`` object, we may still return ``nil`` afterwards in case of any error. Because of this, the ``controlPost`` ``reverter`` won't have any ``joinInfo`` object to use for removing itself from the cluster.

Because of this issue, if the cluster join operations fails, that node may no longer be able to join the cluster, as it appears to have already joined the cluster.

This commit addresses this issue by returning the ``joinInfo`` object after it exists.

### CODE REVIEW

**Review by masnax — CHANGES_REQUESTED** [review]
Thanks for catching this! 

One small maintainability improvement I'd suggest is rather than returning the struct in the error blocks, which we will have to remember to do if we ever want to extend this function, can you instead split `joinWithToken` into two parts? 

The first function can return `joinInfo` to the caller, and the second function (beginning with the call to `WriteCert`) can be called right afterward, taking joinInfo as an argument.

**Comment by claudiubelu** [comment]
> Thanks for catching this!
> 
> One small maintainability improvement I'd suggest is rather than returning the struct in the error blocks, which we will have to remember to do if we ever want to extend this function, can you instead split `joinWithToken` into two parts?
> 
> The first function can return `joinInfo` to the caller, and the second function (beginning with the call to `WriteCert`) can be called right afterward, taking joinInfo as an argument.

Done

**Comment by claudiubelu** [comment]
> Thanks for catching this!
> 
> One small maintainability improvement I'd suggest is rather than returning the struct in the error blocks, which we will have to remember to do if we ever want to extend this function, can you instead split `joinWithToken` into two parts?
> 
> The first function can return `joinInfo` to the caller, and the second function (beginning with the call to `WriteCert`) can be called right afterward, taking joinInfo as an argument.

Done

**Comment by bschimke95** [comment]
@masnax is any additional change required for this to land? Otherwise, I'd love to see this PR merged.

**Review by masnax — APPROVED** [review]
@bschimke95 Nope, lgtm, thanks @claudiubelu for the fix!

**Comment by masnax** [comment]
@claudiubelu Seems you haven't properly ssh/gpg signed your commits. Can you please do so?

**Comment by claudiubelu** [comment]
> @claudiubelu Seems you haven't properly ssh/gpg signed your commits. Can you please do so?

done

**Pull request merged**
